package io.corona.api.constants;

public class StringConstant {
	public static final String TOTAL_CASES = "totalCases";
	public static final String ALL_CASES = "allCases";
	public static final String TOTAL_POPULATION = "totalPopulation";
	public static final String TOTAL_TODAYS_DEATH = "totalTodaysDeath";
	public static final String TOTAL_TODAYS_RECOVERY = "totalTodaysRecovery";
	public static final String TOTAL_TODAYS = "totalTodays";
	public static final String TOTAL_DEATHS = "totalDeaths";
	public static final String TOTAL_RECOVERY = "totalRecovery";
	public static final String INDIAN_STATES = "indianStates";
	public static final String INDIAN_STATE_WISE = "indianStateWise";
	public static final String COUNTRIES_INDIA_STATEWISE = "/countries/india/statewise";
	public static final String COUNTRY_NAME = "countryName";
	public static final String COUNTRY_DTO = "countryDTO";
	public static final String COUNTRIES_COUNTRY = "/countries/{country}";
	public static final String COUNTRIES = "/countries";
	public static final String INDEX = "index";
	public static final String CORONA_API = "/corona-api";
	public static final String COUNTRY_WISE = "countryWise";
	public static final String SURVEY_MAP = "surveyMap";
	public static final String BAR_GRAPH = "barGraph";
	public static final String PIE_CHART = "pieChart";
	public static final String GRAPHS_INDIA_PIE_CHART = "/graphs/india/pieChart";
	public static final String GRAPHS_INDIA_DISPLAY_BAR_GRAPH = "/graphs/india/displayBarGraph";
	public static final String _1 = "1 * * * * *";
	public static final String THIS_CONSOLIDATES_STATISTICS_FOR_INDIA_TO_DISPLAY_PIE_CHART = "This consolidates statistics for India to display pie chart";
	public static final String THIS_CONSOLIDATES_STATISTICS_FOR_INDIA_TO_DISPLAY_BAR_GRAPH = "This consolidates statistics for India to display bar graph";
	public static final String THIS_CONSOLIDATES_STATISTICS_FOR_INDIA_STATE_WISE = "This consolidates statistics for India state-wise";
	public static final String THIS_CONSOLIDATES_STATISTICS_FOR_A_SPECIFIC_COUNTRY = "This consolidates statistics for a specific country";
	public static final String THIS_CONSOLIDATES_STATISTICS_FOR_ALL_COUNTRIES = "This consolidates statistics for all countries";
	public static final String TOP_FIVE_COUNTRIES = "topFiveCountries";
	public static final String LINE_GRAPH = "lineGraph";
	public static final String GRAPHS_INDIA_LINE_GRAPH = "/graphs/india/lineGraph";
	public static final String DEATH_CASE_MAP = "deathCaseMap";
	public static final String RECOVERED_CASE_MAP = "recoveredCaseMap";
	public static final String SURVEY_MAP2 = "surveyMap2";
	public static final String STATE_NAME = "stateName";
	public static final String INDIAN_DISTRICTS = "indianDistricts";
	public static final String INDIAN_DISTRICT_WISE = "indianDistrictWise";
	public static final String INDIA_DISTRICTS_STATE_NAME = "/india/districts/{stateName}";
}
